### ISSUE TITLE
Unclear output and cloud-effects

### ISSUE THREAD

**Issue by robdimsdale** [rosenhouse/tubes#3]
I ran tubes with credentials to an admin user, and it didn't seem to do anything on the cloud and the output isn't very obvious to me:

```
AWS_DEFAULT_REGION=us-east-1 AWS_ACCESS_KEY_ID=xxx AWS_SECRET_ACCESS_KEY='xxx'  ./tubes -n my-env up
Creating keypair...
Looking for latest AWS NAT box AMI...
Latest NAT box AMI is "ami-b0210ed8"
Upserting stack...
timed out waiting for stack change to complete (max 5m0s, UPDATE_COMPLETE_CLEANUP_IN_PROGRESS)
```

What happened here?

**Comment by rosenhouse** [comment]
To see the effects, check out CloudFormation console.

But yeah, AWS was being slower than the code expects.  I've seen this timeout once in a blue-moon.  

[Here's the error line](https://github.com/rosenhouse/tubes/blob/835429b6a56e6e23aac5056393f46a22fd94d001/lib/awsclient/stack_wait.go#L43)

If you trace `CloudFormationWaitTimeout` back up, you'll see [this awesomeness](https://github.com/rosenhouse/tubes/blob/835429b6a56e6e23aac5056393f46a22fd94d001/lib/awsclient/client.go#L78-L80).  You could just bump the default there to fix the problem.

BUT, above that is [some config which doesn't explicitly set the value](https://github.com/rosenhouse/tubes/blob/835429b6a56e6e23aac5056393f46a22fd94d001/application/commands/common.go#L56-L66).

I think the right approach would be to extract the timeout as a config option on [`commands.AWSConfig`](https://github.com/rosenhouse/tubes/blob/835429b6a56e6e23aac5056393f46a22fd94d001/application/commands/inputs.go#L28-L33) and include the default there.  Then just pass one value through the  `Config` and into the `AWSClient` constructor.

**Comment by robdimsdale** [comment]
Ok I see. In this particular case, there was nothing in the Cloudformation console, probably because it failed really early on.

I took a quick look over the links you provided above, and I agree that you probably want to expose a single default in a single place, and that `commands.AWSConfig` is a good place for that.

As a separate question, I'm trying to use this to make a bosh director in an existing VPC, and I assume this tool doesn't yet do that?

**Comment by rosenhouse** [comment]
> As a separate question, I'm trying to use this to make a bosh director in an existing VPC, and I assume this tool doesn't yet do that?

Right, and it'd be a discussion as to whether it ever should.  Part of the "magic" is that it "knows" (via hardcoded string constants) the logical names of certain resources in a CloudFormation stack that it itself created.  That's how it pulls in the correct subnet-id into a BOSH manifest, for example.  If the stack came from elsewhere, it's not clear how tubes should discover which resources belong where.

**Comment by rosenhouse** [comment]
Also, the "creating key pair" line means that it created an SSH keypair in EC2.

And `UPDATE_COMPLETE_CLEANUP_IN_PROGRESS` doesn't mean that CloudFormation failed.  I believe that it means the stack update succeeded, and it's probably removing stale resources.  I'm surprised to hear that the stack doesn't show up in the CloudFormation Console.

This is an unfortunate case, because at that point `tubes` could totally just generate the BOSH init manifest. But right now, it just hard fails ([see here](https://github.com/rosenhouse/tubes/blob/835429b6a56e6e23aac5056393f46a22fd94d001/application/up.go#L60-L63))

**Comment by robdimsdale** [comment]
I took a further look and did in fact see the keypair. It's possible the stack was present - I think I was using the same name as an existing stack which would explain why I didn't see another stack.

As to whether tubes should ever work with an existing VPC, I think I agree it's quite expensive, but it also could be quite valuable, as it allows composition of resources, instead of tubes having to know about the entire state of the world. What I mean by that is instead of having tubes know about all possible states, you can feed tubes an existing state (e.g. cloudformation.json) and it can ensure that it builds upon that state. This allows e.g. starting from custom cloudformation, but then using tubes to add a bosh-director to the mix.

Tubes can support a standalone bosh director, and also a concourse instance, but what if I want to add a bosh director to some other, custom infrastructure? I'd love for tubes to make a valid bosh-lite manifest given a cloudformation script for existing VPC

**Comment by rosenhouse** [comment]
I think the code in #4 helps address your primary issues with unclear output & timeouts, so I'm going to close this issue.

Feel free to continue the discussion about supporting existing VPCs either in a new issue.  I'd be curious to hear more about the use case -- for example why its important that the existing VPC stay in place, rather than being torn-down and replaced.  Also, what other resources, beyond the VPC itself, would `tubes` depend on rather than create?  (e.g. does `tubes` make its own subnets?  NAT box?   security groups?)
